### ISSUE TITLE
希望能给出安装机器的推荐配置以及机器数量

### ISSUE THREAD

**Issue by chyun** [qlangtech/tis-solr#22]
希望能给出安装机器的推荐配置以及机器数量

**Comment by baisui1981** [comment]
机器数量及规格要求，在这里有，请查看[服务器节点清单](http://tis.pub/docs/install/requirement/#%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%8A%82%E7%82%B9%E6%B8%85%E5%8D%95)。
另外，如果你集群中已经安装了Zookeeper，hadoop HDFS，yarn容器，spark或者hive环境的话，可跳过不安装。只需要安装tis-console，assemble，solr节点（tis-console，assemble，solr节点可部署在单节点，不差钱的话也可部署在多独立节点）
